"""Emission of Luce fragments, ORDER files and the namemap for one package."""
import collections
import os
import re

import names as N
import scope as S
from typemap import render, walk_refs, has_unmapped, unmapped_notes, spelling_of, Ref, B
from plan import lib_of, CORE_LIBS, tpn
from clangenv import PIN

BAR = '#' + '=' * 94
MARK_WIDTH = 97


def header_box(title, desc_lines):
    out = [BAR, '#', f'#   {title}', '#', '#   DESCRIPTION:']
    for line in desc_lines:
        out.append('#       ' + line if line else '#')
    out += ['#', BAR, '']
    return out


def mark(name):
    s = f'# mark: {name} '
    return s + '=' * max(4, MARK_WIDTH - len(s))


def wrap_desc(text, width=86):
    words = text.split()
    lines, cur = [], ''
    for w in words:
        if len(cur) + len(w) + 1 > width:
            lines.append(cur)
            cur = w
        else:
            cur = (cur + ' ' + w).strip()
    if cur:
        lines.append(cur)
    return lines


PACKAGE_ROOT = {p: 'luce_browser_' + p for p in S.PACKAGES}


def fragment_path_for_file(module, path):
    """Directory (relative to the module dir) and stem for a donor file's types fragment."""
    stem = S.stem(path)
    base = N.snake(os.path.basename(stem))
    if module == 'web':
        rel = stem
        for prefix in ('Libraries/LibWeb/', 'Build/Libraries/LibWeb/'):
            if rel.startswith(prefix):
                sub = os.path.dirname(rel[len(prefix):])
                subdir = '/'.join(N.snake(p) for p in sub.split('/') if p)
                if rel.startswith('Build/'):
                    subdir = 'generated/' + subdir if subdir else 'generated'
                return subdir, base
        lib = N.snake(lib_of(path) or 'external')
        return 'external/' + lib, base
    if path.startswith('Build/'):
        return '', 'generated_' + base
    return '', base


class Emitter:
    def __init__(self, planner, namer, package, outdir):
        self.p = planner
        self.nm = namer
        self.package = package
        self.out = outdir
        self.modules = [m for m in S.MODULES if S.PACKAGE_OF[m] == package and m not in S.FOREIGN_MODULES]
        self.refs_used = collections.defaultdict(set)
        self.stats = collections.Counter()
        self.namemap = []
        self.extra_imports = collections.defaultdict(set)
        self.baseline = None   # baseline.Baseline of the ported package (class ids, names)

    # ---- rendering helpers --------------------------------------------------------------------
    def names_cb(self, module):
        def cb(key):
            d = self.p.decls[key]
            if d.module != module:
                self.refs_used[module].add(d.module)
            return d.module, d.name
        return cb

    def R(self, ref, module):
        return render(ref, module, self.names_cb(module))

    def qual(self, module, target_module, name):
        if target_module != module:
            self.refs_used[module].add(target_module)
            return f'{target_module}.{name}'
        return name

    def dname(self, key, module):
        d = self.p.decls[key]
        return self.qual(module, d.module, d.name)

    def visible_ref(self, ref, module):
        for key, bv in walk_refs(ref, True):
            d = self.p.decls.get(key)
            if d is None:
                return False
            if not self.p.visible(module, d.module):
                return False
        return True

    # ---- per module ----------------------------------------------------------------------------
    def emit(self):
        p = self.p
        for module in self.modules:
            self.emit_module(module)

    def emit_module(self, module):
        p = self.p
        frags = collections.OrderedDict()   # relpath -> dict(title, desc, blocks[(sortkey, lines)])

        def frag(rel, title, desc):
            f = frags.get(rel)
            if f is None:
                f = {'title': title, 'desc': desc, 'blocks': [], 'files': set()}
                frags[rel] = f
            return f

        decls = [d for d in p.decls.values() if d.module == module and d.kind != 'ovr']
        for d in decls:
            if d.kind in ('variant', 'traits'):
                rel = 'types_variants.lucb' if d.kind == 'variant' else 'types_traits.lucb'
                if module == 'web':
                    rel = 'generated/' + rel
                f = frag(rel, rel.split('/')[-1][:-5] + ' - ' + (
                    'Variant<...> instantiations as payload enums' if d.kind == 'variant' else
                    'hash traits of the key types of HashMap/HashTable instantiations'),
                    ['Generated by the skeleton generator (DESIGN.md §2.6): one declaration per distinct',
                     f'instantiation the phase-1 declarations use, at donor commit {PIN}.'])
                lines = self.emit_variant(d, module) if d.kind == 'variant' else self.emit_traits(d, module)
                f['blocks'].append(((d.name,), lines))
                continue
            path = d.file or ''
            sub, base = fragment_path_for_file(module, path) if path else ('', 'external')
            rel = (sub + '/' if sub else '') + 'types_' + base + '.lucb'
            f = frag(rel, 'types_' + base + ' - declarations of ' + (path or 'external declarations'), None)
            if path:
                f['files'].add(path)
            lines = self.emit_decl(d, module)
            if lines:
                f['blocks'].append(((d.line, d.q, str(d.key)), lines))
        for v, ref in p.var_tasks:
            key_mod = self.var_module(v, ref)
            if key_mod != module:
                continue
            sub, base = fragment_path_for_file(module, v['file'])
            rel = (sub + '/' if sub else '') + 'types_' + base + '.lucb'
            f = frag(rel, 'types_' + base + ' - declarations of ' + v['file'], None)
            f['files'].add(v['file'])
            f['blocks'].append(((v['line'], v['q'], v['usr']), self.emit_var(v, ref, module)))
        # functions by region
        funcs = [F for F in p.funcs if F.module == module]
        funcs.sort(key=lambda F: (self.fn_sort_file(F), self.fn_line(F), F.name))
        for F in funcs:
            if F.region:
                rid, rname, _ = F.region
                rel = f'stub_{rid}_{rname}.lucb'
                title = f'stub_{rid}_{rname} - typed stubs of region {rid} ({rname})'
            else:
                rel = 'stub_closure.lucb'
                title = 'stub_closure - stubs of virtual functions of classes outside the phase-1 files'
            if module == 'web':
                rel = 'stubs/' + rel
            f = frag(rel, title, None)
            f['files'].add(self.fn_file(F))
            f['blocks'].append(((self.fn_sort_file(F), self.fn_line(F), F.name), self.emit_func(F, module)))
        self.write_module(module, frags)

    def fn_file(self, F):
        d = self.p.defs.get(F.fn['usr'])
        return d['file'] if d and d.get('file') else F.fn['file']

    def fn_line(self, F):
        """The line of the function's definition (its C++ order), else of its declaration."""
        d = self.p.defs.get(F.fn['usr'])
        return d['line'] if d and d.get('line') else F.fn['line']

    def fn_sort_file(self, F):
        return S.stem(self.fn_file(F))

    def var_module(self, v, ref):
        return v.get('_module') or 'web'

    # ---- declarations ---------------------------------------------------------------------------
    def emit_decl(self, d, module):
        if d.kind == 'record':
            return self.emit_record(d, module)
        if d.kind == 'opaque':
            return self.emit_opaque(d, module)
        if d.kind == 'enum':
            return self.emit_enum(d, module)
        if d.kind == 'tmpl':
            return self.emit_tmpl(d, module)
        if d.kind == 'opaque_tmpl':
            r = self.p.tmpl_by_usr[d.key[1]]
            params = [tpn(tp['n']) for tp in r['tparams'] if tp['k'] == 'type']
            self.namemap.append((d.q, module, d.name, self.loc(d), 'opaque generic'))
            return [f'## {d.q} ({self.loc(d)}): opaque in this phase.',
                    f'pub struct {d.name}' + (f'[{", ".join(params)}]' if params else '') + ':',
                    '    pub var opaque_: u8', '']
        if d.kind == 'inst':
            return self.emit_inst(d, module)
        return []

    def clean_q(self, q):
        return re.sub(r'\((unnamed|anonymous) (union|struct|enum|class)? ?at [^)]*\)', r'(anonymous \2)', q or '')

    def loc(self, d):
        return f'{d.file}:{d.line}' if d.file else 'generated'

    def emit_opaque(self, d, module):
        self.stats['opaque'] += 1
        self.namemap.append((d.q, module, d.name, self.loc(d), 'opaque'))
        return [f'## {d.q or d.name} ({self.loc(d)}): opaque in this phase (not in the phase-{S.PHASE} closure).',
                f'pub struct {d.name}:', '    pub var opaque_: u8', '']

    def field_lines(self, fields, module, owner_name, taken, owner_q=''):
        out = []
        idx = 0
        self.last_fields = []
        for fd, ref in fields:
            cut = S.FIELD_CUTS.get((owner_q, fd['n']))
            if cut:
                for fname, ftype, mods in cut:
                    for m in mods:
                        if m != module:
                            self.refs_used[module].add(m)
                    taken.add(fname)
                    out.append(f'    pub var {fname}: {ftype}  # retyped (DESIGN.md §4.1.3): '
                               + one_line(spelling_of(fd['t']))[:80] + f' {fd["n"]}')
                self.stats['retyped_fields'] += 1
                continue
            name = N.field_name(fd['n'] or f'unnamed_{idx}')
            idx += 1
            while name in taken:
                name += '_'
            taken.add(name)
            comment = ''
            if fd.get('bits'):
                if ref.kind == 'b' and ref.name == 'bool':
                    pass
                comment = f'  # bit-field : {fd["bits"]}'
            if has_unmapped(ref):
                ts = 'void*?'
                comment = '  # unmapped: ' + one_line('; '.join(unmapped_notes(ref)))[:120]
                self.stats['unmapped_fields'] += 1
            elif not self.visible_ref(ref, module):
                ts = 'void*?'
                comment = '  # cut (upward reference, DESIGN.md §4.1.3): ' + one_line(spelling_of(fd['t']))[:100]
                self.stats['cut_fields'] += 1
            else:
                ts = self.R(ref, module)
                self.last_fields.append((fd, name, ref))
            init = fd.get('init')
            if init and not comment:
                init = one_line(init)
                if len(init) > 60:
                    init = init[:57] + '...'
                comment = f'  # C++ default: {init}'
            out.append(f'    pub var {name}: {ts}{comment}')
        return out

    def emit_record(self, d, module):
        p = self.p
        usr = d.key[1]
        r = p.records[usr]
        self.stats['structs'] += 1
        lines = [mark(d.name), '']
        lines.append(f'## {self.clean_q(d.q)} ({self.loc(d)}).')
        self.namemap.append((self.clean_q(d.q), module, d.name, self.loc(d), 'struct'))
        poly = p.is_poly(usr)
        prim = p.primary(usr)
        is_root = poly and (prim is None or not p.is_poly(prim))
        conf = []
        body_methods = []
        taken = set()
        upcasts = []
        if poly:
            chain = []
            u = usr
            while u is not None and p.is_poly(u):
                chain.append(u)
                pu = p.primary(u)
                if pu is None or not p.is_poly(pu):
                    break
                u = pu
            for a in chain:
                ad = p.decls.get(('rec', a))
                if ad is None:
                    continue
                iname = self.qual(module, ad.module, 'Is' + ad.name)
                conf.append(iname)
                mname = N.snake(ad.name)
                upcasts.append(f'    func {mname}() -> {self.qual(module, ad.module, ad.name)}*: '
                               f'return ({self.qual(module, ad.module, ad.name)}*)&self')
                taken.add(mname)
        traits_k = p.traits_records.get(usr)
        if traits_k is not None and not has_unmapped(traits_k):
            conf.append(self.qual(module, 'ak', 'Traits') + '[' + self.R(traits_k, module) + ']')
        kw = 'union' if r['kind'] == 'union' else 'struct'
        head = f'pub {kw} {d.name}' + (': ' + ', '.join(conf) if conf and kw == 'struct' else '') + ':'
        lines.append(head)
        fields = []
        if is_root:
            fields.append(f'    pub var vtable: const {d.name}VTable*')
            fields.append('    pub var class_id: u16')
        bnames, taken = self.base_fields(usr)
        for role, t, bu, fname in bnames:
            if role in ('primary', 'mixin'):
                bd = p.decls[('rec', bu)]
                fields.append(f'    pub var {fname}: {self.qual(module, bd.module, bd.name)}'
                              + ('  # primary base' if role == 'primary' else '  # mixin base'))
            else:
                ref = p.tr.tr(t, {}, 'field')
                fields.append(f'    pub var {fname}: {self.R(ref, module)}  # base {spelling_of(t)}')
        fields += self.field_lines(d.info.get('fields', []), module, d.name, taken, d.q)
        own_fields = list(self.last_fields)
        if kw == 'union':
            fields = [f.replace('    pub var ', '    pub ', 1) for f in fields]
        if not fields:
            fields.append('    pub var empty_: u8' if kw == 'struct' else '    pub empty_: u8')
        lines += fields
        if traits_k is not None and not has_unmapped(traits_k) and kw == 'struct':
            ks = self.R(traits_k, module)
            kp = f'const ({ks})*' if ks.endswith('*') or ks.endswith('?') else f'const {ks}*'
            lines.append(f'    func hash_of(key: {kp}) -> u32: trap("unported: {d.q}::hash")')
            lines.append(f'    func equals(a: {kp}, b: {kp}) -> bool: trap("unported: {d.q}::equals")')
        if kw == 'struct':
            lines += upcasts
        lines.append('')
        if kw == 'struct':
            lines += self.init_fields(d, module, own_fields)
            lines += self.tree_iterators(d, module)
        if poly:
            lines += self.emit_poly(d, module, is_root)
        return lines

    def init_fields(self, d, module, fields):
        """<class>_init_fields: the C++ default member initializers that are not zero (§2.3)."""
        body = []
        for fd, name, ref in fields:
            init = one_line(fd.get('init') or '')
            if not init:
                continue
            v = init[1:-1].strip() if init.startswith('{') and init.endswith('}') else init
            if v in ('', '0', 'false', 'nullptr', '0.0', '0.0f', '0u', '0ul', 'nullptr_t'):
                continue
            lit = literal_value(init, ref)
            if lit is not None:
                if lit.strip('-') in ('0', '0.0', '0x0'):
                    continue
                body.append(f'    this.{name} = {lit}')
                continue
            if ref.kind == 'decl' and ref.key[0] == 'enum':
                case = self.enum_case(ref.key, v)
                if case is not None:
                    if case[1] != 0:
                        body.append(f'    this.{name} = {self.dname(ref.key, module)}.{case[0]}')
                    continue
            if ref.kind == 'b' and ref.name == 'bool' and v in ('true',):
                body.append(f'    this.{name} = true')
                continue
            body.append(f'    # {name}: C++ default {v[:90]} (not translated by the generator)')
        if not body:
            return []
        s = N.snake(d.name)
        name = f'{s}_init_fields'
        self.stats['init_fields'] += 1
        self.namemap.append((f'{self.clean_q(d.q)} [default member initializers]', module, name, self.loc(d),
                             'init fields'))
        if all(b.lstrip().startswith('#') for b in body):
            body.append('    return')
        return [f'## The non-zero default member initializers of {self.clean_q(d.q)}; the constructor runs them first.',
                f'pub func {name}(this: {d.name}*):'] + body + ['']

    def tree_iterators(self, d, module):
        """for-loop iterators over a TreeNode<T> tree (DESIGN.md §2.9), for the class embedding it."""
        p = self.p
        embeds = [t for role, t, bu in p.eff_bases(d.key[1]) if role == 'embed' and t.get('tq') == 'Web::TreeNode']
        if not embeds:
            return []
        args = embeds[0].get('args') or []
        if len(args) != 1 or args[0].get('usr') != d.key[1]:
            return []
        self.extra_imports[module].add('luce')
        n = d.name
        s = N.snake(n)
        self.stats['tree_iterators'] += 1
        for fn in (f'{s}_children', f'{s}_subtree', f'{s}_inclusive_subtree'):
            self.namemap.append((f'{self.clean_q(d.q)} [TreeNode iteration]', module, fn, self.loc(d), 'iterator'))
        return f'''## `for child in {s}_children(node)`: TreeNode<{d.q.split('::')[-1]}>::for_each_child as a loop (DESIGN.md §2.9).
pub struct {n}Children: luce.Iterable[{n}*, {n}ChildIterator]:
    pub var parent: {n}*

    func iterator() -> {n}ChildIterator:
        return {n}ChildIterator(next_node = self.parent.tree_node.m_first_child)

## The iterator of {n}Children: each child in order.
pub struct {n}ChildIterator: luce.Iterator[{n}*]:
    pub var next_node: {n}*?

    mutating func next() -> {n}*?:
        let node = self.next_node else return none
        self.next_node = node.tree_node.m_next_sibling
        return node

## The children of `node`, first to last.
pub func {s}_children(node: {n}*) -> {n}Children:
    return {n}Children(parent = node)

## `for n in {s}_subtree(node)`: for_each_in_subtree / for_each_in_inclusive_subtree as a loop, in
## pre-order; `skip_children()` on the iterator is TraversalDecision::SkipChildrenAndContinue.
pub struct {n}Subtree: luce.Iterable[{n}*, {n}SubtreeIterator]:
    pub var root: {n}*
    pub var inclusive: bool

    func iterator() -> {n}SubtreeIterator:
        return {n}SubtreeIterator(root = self.root, current = none, inclusive = self.inclusive, started = false,
            skip = false)

## The iterator of {n}Subtree (TreeNode<T>::next_in_pre_order with stay_within = the root).
pub struct {n}SubtreeIterator: luce.Iterator[{n}*]:
    pub var root: {n}*
    pub var current: {n}*?
    pub var inclusive: bool
    pub var started: bool
    pub var skip: bool

    mutating func next() -> {n}*?:
        if not self.started:
            self.started = true
            self.current = self.root
            if self.inclusive:
                return self.root
        let node = self.current else return none
        var next: {n}*? = none
        if not self.skip:
            next = node.tree_node.m_first_child
        self.skip = false
        if next == none:
            var walk: {n}*? = node
            while let at = walk:
                if at == self.root:
                    break
                if let sibling = at.tree_node.m_next_sibling:
                    next = sibling
                    break
                walk = at.tree_node.m_parent
        self.current = next
        return next

    ## Do not descend into the children of the node `next()` returned last.
    mutating func skip_children():
        self.skip = true

## The descendants of `node` in pre-order (not `node` itself).
pub func {s}_subtree(node: {n}*) -> {n}Subtree:
    return {n}Subtree(root = node, inclusive = false)

## `node` and its descendants in pre-order.
pub func {s}_inclusive_subtree(node: {n}*) -> {n}Subtree:
    return {n}Subtree(root = node, inclusive = true)
'''.split('\n')

    def enum_case(self, key, text):
        """(Luce case, value) for a C++ enumerator spelled `text` (`Type :: Invalid`, `Invalid`)."""
        e = self.p.enums.get(key[1])
        if e is None:
            return None
        m = re.fullmatch(r'(?:[A-Za-z_][A-Za-z0-9_]*\s*::\s*)*([A-Za-z_][A-Za-z0-9_]*)', text)
        if not m:
            return None
        cname = m.group(1)
        cmap = self.enum_cases(e)
        return cmap.get(cname)

    def enum_cases(self, e):
        """C++ enumerator -> (Luce case of its value, value), as emit_enum names them."""
        out = {}
        seen_names = set()
        seen_vals = {}
        for cname, val in e['cases']:
            n = N.safe(N.snake(cname))
            if n == 'none':
                n = 'none_'
            while n in seen_names:
                n += '_'
            if val in seen_vals:
                out[cname] = (seen_vals[val], val)
                continue
            seen_names.add(n)
            seen_vals[val] = n
            out[cname] = (n, val)
        return out

    def upcast_chain(self, usr):
        p = self.p
        chain = []
        u = usr
        while u is not None and p.is_poly(u):
            chain.append(u)
            pu = p.primary(u)
            if pu is None or not p.is_poly(pu):
                break
            u = pu
        return chain

    def base_fields(self, usr):
        """[(role, ser, base usr, field name)] of a record's embedded bases, and the member names taken."""
        cache = self.__dict__.setdefault('_base_fields', {})
        if usr in cache:
            return cache[usr]
        p = self.p
        taken = set()
        if p.is_poly(usr):
            for a in self.upcast_chain(usr):
                ad = p.decls.get(('rec', a))
                if ad is not None:
                    taken.add(N.snake(ad.name))
            prim = p.primary(usr)
            if prim is None or not p.is_poly(prim):
                taken |= {'vtable', 'class_id'}
        out = []
        for role, t, bu in p.eff_bases(usr):
            if role in ('primary', 'mixin'):
                fname = N.snake(p.records[bu]['q'].split('::')[-1])
            else:
                ref = p.tr.tr(t, {}, 'field')
                if has_unmapped(ref):
                    continue
                fname = N.snake(t.get('tq', 'base').split('::')[-1])
            fname = N.field_name(fname)
            while fname in taken:
                fname += '_base'
            taken.add(fname)
            out.append((role, t, bu, fname))
        cache[usr] = (out, set(taken))
        return out, set(taken)

    def mixin_offsets(self, usr):
        """{mixin field name: (declaring class usr, field name)} along the primary chain."""
        out = {}
        u = usr
        while u is not None:
            for role, t, bu, fname in self.base_fields(u)[0]:
                if role == 'mixin':
                    key = N.snake(self.p.records[bu]['q'].split('::')[-1])
                    out.setdefault(key, (u, fname, bu))
            u = self.p.primary(u)
        return out

    # ---- polymorphism ---------------------------------------------------------------------------
    def emit_poly(self, d, module, is_root):
        p = self.p
        usr = d.key[1]
        vi = p.vinfo.get(usr, {'slots': [], 'overrides': []})
        out = []
        # interface
        out.append(f'## Upcast to {d.q} (implemented by every struct in its hierarchy).')
        out.append(f'pub interface Is{d.name}:')
        out.append(f'    func {N.snake(d.name)}() -> {d.name}*')
        out.append('')
        # vtable struct
        out.append(f'## Virtual functions introduced by {d.q}.')
        out.append(f'pub struct {d.name}VTable:')
        prim = p.primary(usr)
        if prim is not None and p.is_poly(prim):
            pd = p.decls[('rec', prim)]
            out.append(f'    pub let {self.vt_base_field(prim)}: {self.qual(module, pd.module, pd.name)}VTable')
        else:
            out.append(f'    pub let class_info: const {self.qual(module, "ak", "ClassInfo")}*')
        for fn in vi['slots']:
            F = self.p.func_by_usr.get((usr, fn['usr']))
            if F is None:
                continue
            ps = ', '.join([f'{d.name}*'] + [self.R(r, module) for _, r in F.params])
            ret = self.ret_str(F.ret, module, in_type=True)
            out.append(f'    pub let {N.field_name(F.word)}: func({ps}){ret} = {F.name}')
        out.append('')
        # dispatchers
        root = p.root_of(usr)
        rd = p.decls[('rec', root)]
        for fn in vi['slots']:
            F = self.p.func_by_usr.get((usr, fn['usr']))
            if F is None:
                continue
            pnames = self.param_names(F, module, reserve={'this'})
            params = ', '.join([f'this: {d.name}*'] + [f'{n}: {self.R(r, module)}' for n, (_, r) in zip(pnames, F.params)])
            ret = self.ret_str(F.ret, module)
            vt = f'(const {d.name}VTable*)'
            if root == usr:
                access = f'({vt}this.vtable)'
            else:
                access = f'({vt}(({self.qual(module, rd.module, rd.name)}*)this).vtable)'
            call = f'{access}.{N.field_name(F.word)}(' + ', '.join(['this'] + pnames) + ')'
            out.append(f'## Virtual: {fn["q"]}.')
            out.append(f'pub func {F.dispatcher}({params}){ret}:')
            if F.ret.kind == 'fallible':
                if F.ret.inner.kind == 'b' and F.ret.inner.name == 'unit':
                    out.append(f'    try {call}')
                else:
                    out.append(f'    return try {call}')
            elif F.ret.kind == 'b' and F.ret.name == 'unit':
                out.append(f'    {call}')
            else:
                out.append(f'    return {call}')
            out.append('')
            self.stats['dispatchers'] += 1
            self.namemap.append((fn['q'] + ' [dispatch]', module, F.dispatcher, self.loc(d), 'dispatcher'))
        # vtable instance and class info
        s = N.snake(d.name)
        out.append(f'## The vtable of {d.q}.')
        out.append(f'pub let {s}_vtable: {d.name}VTable = {self.vt_init(usr, usr, module)}')
        out.append('')
        ids, shared_with = self.class_id_range(d)
        mixins_arg = ''
        if module == 'web' and p.is_cell(usr):
            mo = self.mixin_offsets(usr)
            if mo:
                parts = []
                for key, (au, fname, bu) in sorted(mo.items()):
                    ad = p.decls[('rec', au)]
                    parts.append(f'{key} = offsetof({self.qual(module, ad.module, ad.name)}, {fname})')
                out.append(f'## Where {d.q}\'s stateful mixins live inside it (DESIGN.md §2.5).')
                out.append(f'pub let {s}_mixins: MixinOffsets = MixinOffsets({", ".join(parts)})')
                out.append('')
                mixins_arg = f', mixins = (const void*)&{s}_mixins'
        if shared_with is not None:
            out.append(f'## Class information of {d.q}: name, the class id of {shared_with} (it shares its nearest')
            out.append('## numbered ancestor\'s id and is recognized by its ClassInfo), size, vtable.')
        else:
            out.append(f'## Class information of {d.q}: name, class-id range (pre-order), size, vtable.')
        out.append(f'pub let {s}_class: {self.qual(module, "ak", "ClassInfo")} = '
                   f'{self.qual(module, "ak", "ClassInfo")}(name = "{d.q.split("::")[-1]}", '
                   f'first_id = {ids[0]}, last_id = {ids[1]}, size = sizeof({d.name}), '
                   f'vtable = (const void*)&{s}_vtable{mixins_arg})')
        out.append('')
        # the vtables of the polymorphic mixins inside this class, with its overrides (§2.5)
        for key, (au, fname, bu) in sorted(self.mixin_offsets(usr).items()):
            if not p.is_poly(bu):
                continue
            md = p.decls[('rec', bu)]
            out.append(f'## The vtable of the {md.q} mixin inside {d.q}.')
            out.append(f'pub let {s}_{key}_vtable: {self.qual(module, md.module, md.name)}VTable = '
                       f'{self.vt_init(usr, bu, module)}')
            out.append('')
            self.stats['mixin_vtables'] += 1
        # is/as helpers over the root interface (a mixin's are the cross-casts of MixinOffsets instead)
        if usr in p.mixin_usrs:
            self.stats['vtables'] += 1
            return out
        iface = self.qual(module, rd.module, 'Is' + rd.name)
        rm = N.snake(rd.name)
        if shared_with is not None:
            classes = [s] + [N.snake(self.p.decls[('rec', u)].name) for u in self.new_descendants(usr)]
            out.append(f'## is<{d.q}>: the cell\'s ClassInfo is its own' +
                       (' or a subclass\'s.' if len(classes) > 1 else '.'))
            out.append(f'pub func is_{s}[P: {iface}](p: P*) -> bool:')
            out.append(f'    let class_info = p.{rm}().vtable.class_info')
            out.append('    return ' + ' or '.join(f'class_info == &{c}_class' for c in classes))
        else:
            out.append(f'## is<{d.q}>: the class-id range test.')
            out.append(f'pub func is_{s}[P: {iface}](p: P*) -> bool:')
            out.append(f'    let id = p.{rm}().class_id')
            out.append(f'    return id >= {s}_class.first_id and id <= {s}_class.last_id')
        out.append('')
        out.append(f'## as_if<{d.q}>.')
        out.append(f'pub func as_if_{s}[P: {iface}](p: P*) -> {d.name}*?:')
        out.append(f'    if is_{s}(p): return ({d.name}*)p')
        out.append('    return none')
        out.append('')
        out.append(f'## as<{d.q}> (verify_cast).')
        out.append(f'pub func as_{s}[P: {iface}](p: P*) -> {d.name}*:')
        out.append(f'    return as_if_{s}(p) else trap("as<{esc(d.q)}> failed")')
        out.append('')
        self.stats['vtables'] += 1
        out += self.creation_helpers(d, module)
        return out

    def class_id_range(self, d):
        """(first, last) class ids of a polymorphic class, and the ancestor whose id it shares (None
        when it has its own range). Against a baseline, a ported class keeps its ids; a new class
        whose hierarchy is numbered shares its nearest numbered ancestor's id (see baseline.py)."""
        usr = d.key[1]
        own = self.p.class_ids.get(usr, (0, 0))
        b = self.baseline
        if b is None or d.module != 'web':
            return own, None
        known = b.class_ids.get(N.snake(d.name) + '_class')
        shared = None
        u = self.p.primary(usr)
        while u is not None and self.p.is_poly(u):
            ad = self.p.decls.get(('rec', u))
            if ad is not None:
                key = N.snake(ad.name) + '_class'
                ids = b.class_ids.get(key if ad.module == 'web' else f'{ad.module}.{key}')
                if ids is not None:
                    shared = ((ids[0], ids[0]), ad.q)
                    break
            u = self.p.primary(u)
        if known is not None:
            # a class a region declared by hand with an ancestor's id (or 0) shares that id
            if shared is not None and (known == shared[0] or known == (0, 0)):
                return shared
            return known, None
        if shared is not None:
            return shared
        return own, None

    def new_descendants(self, usr):
        """The full polymorphic classes below `usr` that the baseline does not number yet."""
        out = []
        for dd in self.p.decls.values():
            if dd.kind != 'record' or dd.level != 'full' or dd.key[1] == usr or not self.p.is_poly(dd.key[1]):
                continue
            if self.class_id_range(dd)[1] is None:
                continue
            u = self.p.primary(dd.key[1])
            while u is not None:
                if u == usr:
                    out.append(dd.key[1])
                    break
                u = self.p.primary(u)
        return sorted(out, key=lambda x: self.p.records[x]['q'])

    def creation_helpers(self, d, module):
        """realm_create_<class> per constructor of a concrete cell class (DESIGN.md §2.3)."""
        p = self.p
        usr = d.key[1]
        r = p.records[usr]
        if module != 'web' or r.get('abstract') or not p.is_cell(usr) or ('rec', self.realm_usr) not in p.decls:
            return []
        out = []
        ctors = [F for F in p.funcs if F.owner_key == d.key and F.kind == 'construct' and F.module == module]
        realm = self.dname(('rec', self.realm_usr), module)
        s = N.snake(d.name)
        for F in ctors:
            suffix = F.word[len('construct'):]
            name = f'realm_create_{s}{suffix}'
            n = 2
            while name in self.module_names[module]:
                name = f'realm_create_{s}{suffix}_{n}'
                n += 1
            self.module_names[module].add(name)
            pnames = self.param_names(F, module, reserve={'this', 'realm'})
            ps = [f'realm: {realm}*'] + [f'{pn}: {"void*?" if has_unmapped(rf) else self.R(rf, module)}'
                                        for pn, (_, rf) in zip(pnames, F.params)]
            args = ', '.join(['this'] + pnames)
            out += [f'## realm.create<{d.q}>(...): allocate under DeferGC, construct, then initialize(realm).',
                    f'pub func {name}({", ".join(ps)}) -> {d.name}*:',
                    f'    let this = ({d.name}*)web_allocate_cell(realm, &{s}_class)',
                    f'    {F.name}({args})',
                    '    web_initialize_cell(this.cell(), realm)',
                    '    return this', '']
            self.namemap.append((f'{d.q} [realm.create]', module, name, self.loc(d), 'creation helper'))
            self.stats['creation_helpers'] += 1
        return out

    def vt_base_field(self, prim_usr):
        return N.snake(self.p.records[prim_usr]['q'].split('::')[-1]) + '_vtable'

    def vt_init(self, cls, level, module):
        p = self.p
        ld = p.decls[('rec', level)]
        parts = []
        prim = p.primary(level)
        if prim is not None and p.is_poly(prim):
            parts.append(f'{self.vt_base_field(prim)} = {self.vt_init(cls, prim, module)}')
        else:
            cd = p.decls[('rec', cls)]
            parts.append(f'class_info = &{self.qual(module, cd.module, N.snake(cd.name) + "_class")}')
        vi = p.vinfo.get(level, {'slots': []})
        for fn in vi['slots']:
            impl = self.resolve_impl(cls, level, fn)
            if impl is None:
                continue
            F = impl
            default = p.func_by_usr.get((level, fn['usr']))
            if default is None or F is default:
                continue
            parts.append(f'{N.field_name(default.word)} = {self.qual(module, F.module, F.name)}')
        return f'{self.qual(module, ld.module, ld.name)}VTable(' + ', '.join(parts) + ')'

    def resolve_impl(self, cls, level, slot_fn):
        p = self.p
        u = cls
        while u is not None:
            vi = p.vinfo.get(u)
            if vi:
                for fn, (iu, ifn) in vi['overrides']:
                    if iu == level and ifn['usr'] == slot_fn['usr']:
                        F = p.func_by_usr.get((u, fn['usr']))
                        if F is not None:
                            return F
            if u == level:
                return p.func_by_usr.get((level, slot_fn['usr']))
            u = p.primary(u)
        return None

    # ---- enums, variants, traits, templates ------------------------------------------------------
    def emit_enum(self, d, module):
        e = self.p.enums[d.key[1]]
        self.stats['enums'] += 1
        self.namemap.append((self.clean_q(d.q), module, d.name, self.loc(d), 'enum'))
        under = e['under']
        ut = under.get('n') if under.get('k') == 'b' else 'i32'
        ut = {'char': 'i8', 'bool': 'u8', 'u128': 'u64', 'i128': 'i64', 'f32': 'i32', 'f64': 'i64'}.get(ut, ut)
        if ut not in ('u8', 'u16', 'u32', 'u64', 'i8', 'i16', 'i32', 'i64', 'usize', 'isize'):
            ut = 'i32'
        values = [v for _, v in e['cases']]
        if values and min(values) < 0 and ut.startswith('u'):
            ut = 'i64'
        if ut.startswith('u'):
            e_cases = [(n, v & ((1 << {'u8': 8, 'u16': 16, 'u32': 32, 'u64': 64, 'usize': 64}[ut]) - 1)) for n, v in e['cases']]
        else:
            e_cases = e['cases']
        lines = [f'## {self.clean_q(d.q)} ({self.loc(d)}).']
        if not e_cases:
            lines += [f'pub type {d.name} = {ut}', '']
            return lines
        lines.append(f'pub enum {d.name} as {ut}:')
        seen_names = set()
        seen_vals = {}
        aliases = []
        for cname, val in e_cases:
            n = N.safe(N.snake(cname))
            if n == 'none':
                n = 'none_'
            while n in seen_names:
                n += '_'
            if val in seen_vals:
                aliases.append((n, cname, seen_vals[val]))
                continue
            seen_names.add(n)
            seen_vals[val] = n
            lines.append(f'    {n} = {val}')
        lines.append('')
        for n, cname, target in aliases:
            lname = N.safe(N.snake(d.name) + '_' + n)
            lines.append(f'## {d.q}::{cname} (a second name for {target}).')
            lines.append(f'pub let {lname}: {d.name} = {d.name}.{target}')
            self.alias_lets.setdefault(module, set()).add(lname)
        if aliases:
            lines.append('')
        return lines

    def emit_variant(self, d, module):
        info = self.p.variant_info[d.key]
        self.stats['variants'] += 1
        cases = []
        seen = set()
        for it in info['items']:
            if it.kind == 'decl' and self.p.decls[it.key].q == 'AK::Empty':
                n = 'empty'
                payload = None
            else:
                n = N.safe(N.snake(self.nm.short_ref(it)))
                payload = self.R(it, module)
            if n == 'none':
                n = 'none_'
            while n in seen:
                n += '_'
            seen.add(n)
            cases.append(f'    {n}' + (f'(value: {payload})' if payload else ''))
        alias = ', '.join(sorted(info['aliases'])) or 'no alias'
        self.namemap.append(('Variant<' + ', '.join(self.nm.short_ref(i) for i in info['items']) + '>',
                             module, d.name, 'generated', 'variant'))
        return [f'## AK::Variant<...> ({alias}).', f'pub enum {d.name}:'] + cases + ['']

    def emit_traits(self, d, module):
        kref = self.p.traits_info[d.key]
        ks = self.R(kref, module)
        kp = f'const ({ks})*' if ks.endswith('*') or ks.endswith('?') else f'const {ks}*'
        tr = self.qual(module, 'ak', 'Traits')
        self.stats['traits'] += 1
        return [f'## AK::Traits<{ks}>: AK\'s hash and equality for the key type.',
                f'pub struct {d.name}: {tr}[{ks}]:', '    var empty_: u8',
                f'    func hash_of(key: {kp}) -> u32: trap("unported: AK::Traits<{ks}>::hash")',
                f'    func equals(a: {kp}, b: {kp}) -> bool: trap("unported: AK::Traits<{ks}>::equals")', '']

    def emit_tmpl(self, d, module):
        r = self.p.tmpl_by_usr[d.key[1]]
        params = [tpn(tp['n']) for tp in r['tparams'] if tp['k'] == 'type']
        self.stats['generic_structs'] += 1
        self.namemap.append((d.q, module, d.name, self.loc(d), 'generic struct'))
        kw = 'union' if r['kind'] == 'union' else 'struct'
        head = f'pub struct {d.name}' + (f'[{", ".join(params)}]' if params else '') + ':'
        taken = set()
        fields = []
        for role, t, bu in self.p.eff_bases(d.key[1]):
            if role in ('primary', 'mixin'):
                bd = self.p.decls[('rec', bu)]
                fname = N.snake(self.p.records[bu]['q'].split('::')[-1])
                taken.add(fname)
                fields.append(f'    pub var {fname}: {self.qual(module, bd.module, bd.name)}')
        fields += self.field_lines(d.info.get('fields', []), module, d.name, taken)
        if not fields:
            fields = ['    pub var empty_: u8']
        return [mark(d.name), '', f'## {d.q} ({self.loc(d)}): a generic struct.', head] + fields + ['']

    def emit_inst(self, d, module):
        info = self.p.inst_info[d.key]
        self.stats['instances'] += 1
        args = ', '.join(self.R(a, module) for a in info['args'])
        self.namemap.append((d.q + '<' + ', '.join(spelling_of(a) for a in info['targs']) + '>', module, d.name,
                             self.loc(d), 'instantiation'))
        fields = self.field_lines(d.info.get('fields', []), module, d.name, set())
        if not fields:
            fields = ['    pub var empty_: u8']
        return [mark(d.name), '', f'## {d.q}<{args}> ({self.loc(d)}), instantiated (DESIGN.md §2.8).',
                f'pub struct {d.name}:'] + fields + ['']

    def emit_var(self, v, ref, module):
        name = v['_name']
        self.stats['vars'] += 1
        self.namemap.append((v['q'], module, name, f'{v["file"]}:{v["line"]}', 'variable'))
        init = (v.get('init') or '').replace('\n', ' ')
        if has_unmapped(ref) or not self.visible_ref(ref, module):
            ts = 'void*?'
        else:
            ts = self.R(ref, module)
        lit = literal_value(init, ref)
        lines = [f'## {v["q"]} ({v["file"]}:{v["line"]}).']
        if lit is not None and v.get('constexpr'):
            lines.append(f'pub let {name}: {ts} = {lit}')
        elif lit is not None:
            lines.append(f'pub var {name}: {ts} = {lit}')
        else:
            if init:
                lines.append(f'# C++ initializer: {one_line(init)[:100]}')
            if self.zeroable(ref):
                lines.append(f'pub var {name}: {ts}')
            else:
                ts2 = ts if ts.endswith('?') else (f'({ts})?' if ts.endswith(']') or ts.startswith('func') else ts + '?')
                lines.append(f'pub var {name}: {ts2}  # not zeroable in Luce: optional until initialized')
        lines.append('')
        return lines

    def zeroable(self, ref, depth=0):
        if depth > 20:
            return True
        k = ref.kind
        if k == 'b':
            return True
        if k == 'ptr' or k == 'func':
            return ref.nullable
        if k in ('opt', 'span', 'unmapped'):
            return True
        if k == 'arr':
            return self.zeroable(ref.inner, depth + 1)
        if k == 'tuple':
            return all(self.zeroable(i, depth + 1) for i in ref.items)
        if k == 'decl':
            d = self.p.decls[ref.key]
            if d.kind in ('opaque', 'ovr'):
                return d.name not in ('Function0',) or True
            if d.kind == 'enum':
                e = self.p.enums[d.key[1]]
                return any(v == 0 for _, v in e['cases']) or not e['cases']
            if d.kind == 'variant':
                it = self.p.variant_info[d.key]['items'][0]
                return it.kind == 'decl' and self.p.decls[it.key].q == 'AK::Empty'
            if d.kind in ('record', 'tmpl', 'inst'):
                if d.kind == 'record' and self.p.is_poly(d.key[1]):
                    return False
                for fd, fr in d.info.get('fields', []):
                    if has_unmapped(fr):
                        continue
                    if not self.zeroable(fr, depth + 1):
                        return False
                if d.kind in ('record', 'tmpl'):
                    for role, t, bu in self.p.eff_bases(d.key[1]):
                        if role in ('primary', 'mixin') and not self.zeroable(Ref('decl', key=('rec', bu)), depth + 1):
                            return False
                return True
            return True
        return True

    # ---- functions ------------------------------------------------------------------------------
    def ret_str(self, ret, module, in_type=False):
        if ret.kind == 'b' and ret.name == 'unit':
            return ' -> unit' if in_type else ''
        if has_unmapped(ret):
            return ' -> void*?'
        if in_type and ret.kind == 'fallible' and ret.inner.kind == 'b' and ret.inner.name == 'unit':
            return ' -> unit!'
        return ' -> ' + self.R(ret, module)

    def override_pnames(self, usr):
        """Parameter names of some definition of the virtual `usr` (a pure virtual declared without
        names takes them from an override's definition)."""
        cache = self.__dict__.setdefault('_override_pnames', None)
        if cache is None:
            cache = {}
            for vi in self.p.vinfo.values():
                for fn, (iu, ifn) in vi['overrides']:
                    d = self.p.defs.get(fn['usr'])
                    if d and d.get('pnames') and all(d['pnames']):
                        cache.setdefault(ifn['usr'], d['pnames'])
            self._override_pnames = cache
        return cache.get(usr)

    def param_names(self, F, module, reserve=()):
        d = self.p.defs.get(F.fn['usr'])
        pn = d.get('pnames') if d else None
        if not pn or not all(pn):
            pn = self.override_pnames(F.fn['usr']) or pn
        raw = []
        kept = getattr(F, 'kept', None) or list(range(len(F.params)))
        for i, (n, _) in enumerate(F.params):
            name = ''
            oi = kept[i] if i < len(kept) else i
            if pn and oi < len(pn) and pn[oi]:
                name = pn[oi]
            elif n:
                name = n
            raw.append(name or f'arg{i}')
        out = []
        used = set(reserve)
        forbidden = self.module_names[module]
        for n in raw:
            n = N.safe(n)
            while n in used or n in forbidden or n in S.MODULES:
                n += '_'
            used.add(n)
            out.append(n)
        return out

    def emit_func(self, F, module):
        p = self.p
        fn = F.fn
        self.stats['functions'] += 1
        lines = []
        d = p.defs.get(fn['usr'])
        loc = f'{d["file"]}:{d["line"]}' if d else f'{fn["file"]}:{fn["line"]}'
        what = self.clean_q(fn['q'])
        if F.env_key:
            what = f'{fn["q"]} for {p.decls[F.env_key].name}'
        if getattr(F, 'crtp', False):
            what = f'{self.clean_q(fn["q"])} for {p.decls[F.owner_key].q} (CRTP helper)'
        kind_note = ''
        if F.kind == 'impl':
            kind_note = ' (override)' if F.slot else ' (virtual)'
        lines.append(f'## Ported from {loc} {what}{kind_note}.')
        if F.notes:
            lines.append('# unmapped: ' + one_line('; '.join(F.notes))[:150])
        reserve = {'this', 'base'}
        pnames = self.param_names(F, module, reserve=reserve)
        ps = []
        gen = ''
        if F.generic:
            gen = '[' + ', '.join(F.generic) + ']'
        if F.owner_key and 'static' not in fn.get('flags', []):
            od = p.decls[F.owner_key]
            oname = self.qual(module, od.module, od.name)
            if F.owner_key[0] == 'ovr' and getattr(F, 'owner_args', None):
                oname += '[' + ', '.join(F.owner_args) + ']'
            if F.owner_key[0] == 'tmpl':
                r = p.tmpl_by_usr[F.owner_key[1]]
                tps = [tpn(tp['n']) for tp in r['tparams'] if tp['k'] == 'type']
                if tps:
                    oname += '[' + ', '.join(tps) + ']'
            if F.kind == 'impl':
                if F.slot:
                    iu, _ = F.slot
                    idd = p.decls[('rec', iu)]
                    ps.append(f'base: {self.qual(module, idd.module, idd.name)}*')
                else:
                    ps.append(f'this: {oname}*')
            else:
                poly = p.is_poly_key(F.owner_key)
                const = 'const' in fn.get('flags', []) and not poly and F.kind != 'construct'
                ps.append(f'this: {"const " if const else ""}{oname}*')
        defaults_ok = F.kind != 'impl'
        for i, (n, (_, r)) in enumerate(zip(pnames, F.params)):
            if has_unmapped(r):
                ps.append(f'{n}: void*?')
            else:
                dv = self.default_value(F.defaults[i] if i < len(F.defaults) else None, r, module) \
                    if defaults_ok else None
                ps.append(f'{n}: {self.R(r, module)}' + (f' = {dv}' if dv is not None else ''))
        ret = self.ret_str(F.ret, module)
        pub = 'pub '
        if 'internal' in fn.get('flags', []) and not F.owner_key:
            lines.append('# internal linkage in C++: make it private when it is ported.')
        elif F.owner_key and fn.get('access') == 'private' and F.kind != 'impl':
            # (an unused module-private function is a warning, so the stub stays pub)
            lines.append('# private in C++: make it module-private when it is ported.')
        lines.append(f'{pub}func {F.name}{gen}({", ".join(ps)}){ret}:')
        body = self.trivial_body(F, module, pnames)
        if body is None:
            msg = 'pure virtual' if 'pure' in fn.get('flags', []) else 'unported'
            body = [f'    trap("{msg}: {esc(self.clean_q(fn["q"]))}")']
            self.stats['stubs'] += 1
        else:
            self.stats['trivial'] += 1
        lines += body
        lines.append('')
        self.namemap.append((fn['q'] + (f' [{p.decls[F.env_key].name}]' if F.env_key else ''), module, F.name,
                             loc, F.kind))
        return lines

    def default_value(self, text, ref, module):
        """A C++ default argument as a Luce constant expression, or None."""
        if not text:
            return None
        v = one_line(text)
        if v.startswith('{') and v.endswith('}'):
            inner = v[1:-1].strip()
        else:
            inner = v
        if ref.kind in ('opt',) or (ref.kind in ('ptr', 'func') and ref.nullable):
            if inner in ('', 'nullptr', 'OptionalNone', 'OptionalNone {}', 'OptionalNone { }', '{}', 'NULL'):
                return 'none'
            # `Optional<String> {}`, `Optional<T>()`, `GC::Ptr<T> {}`: the empty value
            if re.fullmatch(r'(?:[\w:]+<.*>|OptionalNone)\s*(?:\{\s*\}|\(\s*\))', inner):
                return 'none'
            if ref.kind == 'opt':
                return self.default_value(text, ref.inner, module)
            return None
        lit = literal_value(v, ref)
        if lit is not None:
            return lit
        if ref.kind == 'b' and ref.name == 'bool' and inner in ('true', 'false'):
            return inner
        if ref.kind == 'decl' and ref.key[0] == 'enum':
            case = self.enum_case(ref.key, inner)
            if case is not None:
                return f'{self.dname(ref.key, module)}.{case[0]}'
        if ref.kind == 'decl' and ref.key[0] == 'variant' and re.fullmatch(r'(?:[\w:]+(?:<.*>)?\s*)?(?:\{\s*\}|\(\s*\))|Empty\s*\{\s*\}', inner):
            # a default-constructed Variant<Empty, ...> holds Empty
            first = self.p.variant_info[ref.key]['items'][0]
            if first.kind == 'decl' and self.p.decls[first.key].q == 'AK::Empty':
                return f'{self.dname(ref.key, module)}.empty'
        return None

    def trivial_body(self, F, module, pnames):
        d = self.p.defs.get(F.fn['usr'])
        if not d or 'body' not in d or 'pure' in F.fn.get('flags', []):
            return None
        toks = d['body']
        ret = F.ret
        if F.kind == 'construct':
            return None  # a constructor's mem-initializers are not in its body
        if toks == ['{', '}']:
            if ret.kind == 'b' and ret.name == 'unit':
                return ['    return']
            if ret.kind == 'fallible' and ret.inner.kind == 'b' and ret.inner.name == 'unit':
                return ['    return']
            return None
        if len(toks) == 5 and toks[0] == '{' and toks[1] == 'return' and toks[3] == ';' and toks[4] == '}':
            v = toks[2]
            if v in ('true', 'false') and ret.kind == 'b' and ret.name == 'bool':
                return [f'    return {v}']
            if v == 'nullptr' and ret.kind in ('ptr', 'opt') and (ret.nullable or ret.kind == 'opt'):
                return ['    return none']
            if re.fullmatch(r'\d+', v) and ret.kind == 'b' and ret.name in ('u8', 'u16', 'u32', 'u64', 'i8', 'i16',
                                                                          'i32', 'i64', 'usize', 'isize'):
                return [f'    return {v}']
            if re.fullmatch(r'm_\w+', v) and F.owner_key and F.kind not in ('impl', 'construct') and \
                    F.owner_key[0] == 'rec' and 'static' not in F.fn.get('flags', []):
                od = self.p.decls[F.owner_key]
                for fd, fr in od.info.get('fields', []):
                    if fd['n'] == v and not has_unmapped(fr) and self.visible_ref(fr, od.module) and \
                            self.R(fr, module) == self.R(ret, module) and ret.kind != 'fallible':
                        return [f'    return this.{v}']
        return None

    # ---- output ---------------------------------------------------------------------------------
    def write_module(self, module, frags):
        # The flat package layout: a package's modules live directly under src/ (src/<module>/).
        mdir = os.path.join(self.out, 'src', module)
        os.makedirs(mdir, exist_ok=True)
        order = ['module.lucb']
        support = self.support.get(module)
        if support:
            order.append('support.lucb')
        rels = sorted(frags.keys(), key=lambda r: (
            0 if '/types_' in '/' + r and 'variants' not in r and 'traits' not in r else
            1 if 'variants' in r or 'traits' in r else 2, r))
        bodies = {}
        for rel in rels:
            f = frags[rel]
            f['blocks'].sort(key=lambda b: b[0])
            content = []
            for _, lines in f['blocks']:
                content += lines
            files = sorted(f['files'])
            desc = f['desc']
            if desc is None:
                if rel.split('/')[-1].startswith('stub_'):
                    desc = wrap_desc('Every function of the region with its generated signature and a '
                                     '`trap("unported: ...")` body, in the donor files\' order (DESIGN.md '
                                     '§4.5). A region agent replaces this fragment with ported fragments and '
                                     'deletes it. Generated by the skeleton generator from Ladybird at '
                                     f'{PIN}; do not edit by hand.')
                    desc += [''] + ['Donor files:'] + ['    ' + x for x in files[:40]]
                    if len(files) > 40:
                        desc.append(f'    ... and {len(files) - 40} more')
                else:
                    desc = wrap_desc('Structs, enums, vtables, class information and cast helpers generated '
                                     'from ' + ', '.join(files[:6]) + (' and more' if len(files) > 6 else '') +
                                     f' (Ladybird {PIN}) by the skeleton generator (DESIGN.md §4.4). '
                                     'Regenerate rather than edit, except to fill a field the generator '
                                     'could not map.')
            text = header_box(f['title'], desc) + content
            bodies[rel] = text
            order.append(rel)
        imports = self.import_lines(module)
        mdesc = wrap_desc(MODULE_DESC.get(module, module)) + [''] + LICENSE_LINES
        mtext = header_box(f'{module} - {MODULE_TITLE.get(module, module)}', mdesc) + imports + ['']
        self.write(os.path.join(mdir, 'module.lucb'), mtext)
        if support:
            self.write(os.path.join(mdir, 'support.lucb'), support)
        for rel, text in bodies.items():
            path = os.path.join(mdir, rel)
            os.makedirs(os.path.dirname(path), exist_ok=True)
            self.write(path, text)
        self.write(os.path.join(mdir, 'ORDER'), order)

    def import_lines(self, module):
        """module.lucb's imports: the standard modules by name, a module of this package by its short
        name, another package's modules as from-imports grouped per package (`from
        luce_browser_foundation import ak, gc`)."""
        lines = sorted(f'import {m}' for m in self.extra_imports.get(module, ()))
        foreign = collections.OrderedDict()
        for m in S.MODULES:
            if m not in self.refs_used[module] or m == module:
                continue
            if S.PACKAGE_OF[m] == self.package:
                lines.append(f'import {m}')
            else:
                foreign.setdefault(PACKAGE_ROOT[S.PACKAGE_OF[m]], []).append(m)
        for root, mods in foreign.items():
            lines.append(f'from {root} import {", ".join(mods)}')
        return lines

    def write(self, path, lines):
        text = '\n'.join(lines).rstrip('\n') + '\n'
        text = re.sub(r'\n{3,}', '\n\n', text)
        with open(path, 'w') as f:
            f.write(text)
        self.stats['lines'] += text.count('\n')


LICENSE_LINES = [
    'Copyright (c) 2018-2026, the Ladybird developers.',
    'Copyright (c) 2026 the luce-browser authors.',
    'SPDX-License-Identifier: BSD-2-Clause (see LICENSE)',
]

MODULE_TITLE = {
    'ak': 'the AK subset LibWeb uses (containers, strings, formatting)',
    'gc': 'LibGC: cells, the heap, roots and weak references',
    'web_unicode': 'the LibUnicode pieces LibWeb uses (segmentation, character types)',
    'text_codec': 'LibTextCodec: the WHATWG Encoding decoders and encoders',
    'web_url': 'LibURL: URLs, hosts, origins and sites',
    'web_infra': 'the WHATWG Infra string and byte-sequence helpers',
    'css_syntax': 'CSS Syntax Level 3: tokenizer, tokens, component values',
    'css_data': 'generated CSS data: properties, keywords, enums, units',
    'html_syntax': 'the HTML tokenizer and named character references',
    'gfx': 'LibGfx geometry, color, paths and bitmaps; CSS pixel units',
    'web_fonts': 'fonts: typefaces, font cascades, text layout',
    'raster': 'the CPU rasterizer (a port of tiny-skia)',
    'display_list': 'the display list, its commands and players',
    'web': 'LibWeb: DOM, HTML, CSS, SVG, layout and painting',
}
MODULE_DESC = {
    m: f'Part of the luce-browser port of Ladybird ({PIN}) to luce-base, DESIGN.md §4.1. '
       'The declarations of this module are generated by the local skeleton generator; each region '
       'replaces its stub fragment with ported code.' for m in S.MODULES
}


def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


def one_line(s):
    return re.sub(r'\s+', ' ', s or '').strip()


def literal_value(init, ref):
    if not init:
        return None
    s = init.strip()
    if s.startswith('{') and s.endswith('}'):
        s = s[1:-1].strip()
    if ref.kind == 'b':
        if ref.name == 'bool' and s in ('true', 'false'):
            return s
        if ref.name in ('u8', 'u16', 'u32', 'u64', 'i8', 'i16', 'i32', 'i64', 'usize', 'isize'):
            m = re.fullmatch(r'(-?)\s*(0x[0-9a-fA-F]+|\d+)[uUlL]*', s)
            if m:
                v = m.group(2)
                if v.startswith('0x'):
                    v = '0x' + v[2:].lower()
                if m.group(1) and ref.name.startswith('u'):
                    return None
                return (m.group(1) + v) if m.group(1) else v
        if ref.name in ('f32', 'f64'):
            m = re.fullmatch(r'(-?)\s*(\d+\.\d*(?:[eE][-+]?\d+)?|\d+[eE][-+]?\d+)[fF]?', s)
            if m:
                v = m.group(2)
                if v.endswith('.'):
                    v += '0'
                return m.group(1) + v
    return None
