# Writes painting/tests_paint_recording_cases.lucb (luce-browser-engine) from expected.txt.
# Usage: ./build.sh; ./oracle cases.txt > expected.txt; python3 gen_luce_cases.py > .../web/painting/tests_paint_recording_cases.lucb
import sys
src = open('expected.txt', encoding='utf-8').read().split('\n')
names = [l[2:] for l in open('cases.txt').read().split('\n') if l.startswith('# ') and not l.startswith('# r51b')]
cases = []
for line in src:
    if line.startswith('case '):
        cases.append([line[5:].split('\t'), []])
    elif line and cases:
        cases[-1][1].append(line)

def unescape(s):
    out, i = [], 0
    while i < len(s):
        if s[i] == '\\' and i + 1 < len(s):
            c = s[i + 1]; out.append('\n' if c == 'n' else '\t' if c == 't' else c); i += 2
        else:
            out.append(s[i]); i += 1
    return ''.join(out)

def lit(s):
    r = []
    for ch in s:
        if ch == '\\': r.append('\\\\')
        elif ch == '"': r.append('\\"')
        elif ch == '\n': r.append('\\n')
        elif ch == '\t': r.append('\\t')
        else: r.append(ch)
    return '"' + ''.join(r) + '"'

print('''#==============================================================================================
#
#   tests_paint_recording_cases - display lists and pixels of small documents, from the
#                                 reference build
#
#   DESCRIPTION:
#       Generated by luce-browser-tools/oracles/luce-browser-engine/paint_recording
#       (gen_luce_cases.py over the oracle's expected.txt): for each document, Ladybird's
#       Document::dump_display_list() and the pixels its DisplayListPlayerSkia renders for a
#       screenshot of the page (identical to Ladybird's own headless screenshot of the document
#       with --test-mode, checked locally), cropped to the painted area and run-length encoded
#       ("COUNTxAARRGGBB" tokens, rows top to bottom; the rest of the 800x600 page is white).
#       Also the DevicePixelConverter / DisplayListRecordingContext / ChromeMetrics values.
#
#==============================================================================================
''')
values = None
dl = []
px = []
k = 0
for (args, body) in cases:
    mode = args[0]
    text = '\n'.join(body) + '\n'
    if mode == 'values':
        values = text
    elif mode == 'dl':
        dl.append((names[k], unescape(args[1]), unescape(args[2]), text))
    elif mode.startswith('px '):
        _, x, y, w, h = mode.split()
        rle = ' '.join(l.strip() for l in body if not l.strip().startswith('outside'))
        px.append((names[k], unescape(args[1]), unescape(args[2]), int(w), int(h), rle))
        k += 1
print('## A document of the paint recording cases: its markup and author style sheet, and what the reference build answers.')
print('struct TestPaintRecordingCase:')
print('    let name: str\n    let html: str\n    let css: str\n    let width: i32\n    let height: i32\n    let expected: str\n')
print('## The oracle\'s `values` output (two-space indented lines).')
print('let test_paint_recording_values_expected: str = ' + lit(values) + '\n')
print('## Document::dump_display_list() of each document (two-space indented lines).')
print('let test_paint_recording_display_list_cases: TestPaintRecordingCase[%d] = [' % len(dl))
for name, html, css, text in dl:
    print('    TestPaintRecordingCase(name = %s, html = %s, css = %s, width = 0, height = 0, expected = %s),' % (lit(name), lit(html), lit(css), lit(text)))
print(']\n')
print('## The screenshot pixels of each document: the crop 0,0 WIDTHxHEIGHT, run-length encoded.')
print('let test_paint_recording_pixel_cases: TestPaintRecordingCase[%d] = [' % len(px))
for name, html, css, w, h, rle in px:
    print('    TestPaintRecordingCase(name = %s, html = %s, css = %s, width = %d, height = %d, expected = %s),' % (lit(name), lit(html), lit(css), w, h, lit(rle)))
print(']')
